apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-depl
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8888
      targetPort: 80
    