---
apiVersion: v1
kind: Service
metadata:
  name: service-lb
spec:
  type: loadbalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 3200
      targetPort: 80
      nodePort: 30008
...
