---
apiVersion: v1
kind: Service
metadata:
  name: service-nodeport
spec:
  type: nodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 3200
      targetPort: 80
      nodePort: 30008
...